[project]
name = "stx-decentalised-cloud"
authors = []
description = ""
telemetry = true
requirements = []
cache_dir = "/home/runner/stx-decentralised-cloud/stx-decentalised-cloud/./.requirements"
boot_contracts = ["pox", "costs-v2", "bns"]
[contracts.stx-decentralized-cloud]
path = "contracts/stx-decentralized-cloud.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
